### ISSUE TITLE
"Hardware not supported for Volumetric Materials"

### ISSUE THREAD

**Issue by Erquint** [BlueAmulet/LogNeuter#1]
The `[Error  : Unity Log] Hardware not supported for Volumetric Materials` message is spammed constantly for some Lethal Company players. It absolutely drowns out the log, making it unreadably useless. I suggest you should really figure out how to filter that kind of messages that currently seem unsupported.

**Comment by BlueAmulet** [comment]
Add this to your LogNeuter config
```
[UnityEngine.Rendering.HighDefinition.HDRenderPipeline, Unity.RenderPipelines.HighDefinition.Runtime|FogVolumeVoxelizationPass]
Hardware not supported for Volumetric Materials
```

**Comment by Erquint** [comment]
That seems to work. Shouldn't it be mentioned in README.MD and/or `GenBlockAll` output?

**Comment by BlueAmulet** [comment]
GenBlockAll only scans through the game's log messages, and does not check all dlls for that would take a really long time.
